/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Test.Alumno;
import Test.Archivo;
import Test.Materia;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class CapturaAlumno extends javax.swing.JFrame {

    public CapturaAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        APaternoTxt = new javax.swing.JTextField();
        matriculaTxt = new javax.swing.JTextField();
        AMaternoTxt = new javax.swing.JTextField();
        materiaTxt = new javax.swing.JTextField();
        codMateriaTxt = new javax.swing.JTextField();
        asistenciaTxt = new javax.swing.JTextField();
        u1Txt = new javax.swing.JTextField();
        u2Txt = new javax.swing.JTextField();
        u3Txt = new javax.swing.JTextField();
        u4Txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        errorTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CAPTURAR ALUMNO");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido Paterno");

        jLabel4.setText("Apellido Materno");

        jLabel5.setText("Matricula");

        jLabel6.setText("Materia");

        jLabel7.setText("Codigo Materia");

        jLabel8.setText("Asistencia");

        jLabel9.setText("U1");

        jLabel10.setText("U2");

        jLabel11.setText("U3");

        jLabel12.setText("U4");

        materiaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiaTxtActionPerformed(evt);
            }
        });

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        errorTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(errorTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(59, 59, 59))))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(2, 2, 2))
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jLabel4))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matriculaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(APaternoTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nombreTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AMaternoTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(asistenciaTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(codMateriaTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(materiaTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(u1Txt)
                            .addComponent(u3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(u4Txt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(u2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(APaternoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AMaternoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(matriculaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(materiaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(codMateriaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(asistenciaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(u1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(u2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(u4Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(u3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void materiaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materiaTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Archivo ar = new Archivo();
        int matricula=0;
        int asistencia=0;
        float u1=0,u2=0,u3=0,u4=0;
        boolean datosCorrectos=false;
        /*********************************************************************************************
        ******************esta seccion validará que los campos no esten vacios************************
        *********************************************************************************************/
        if(nombreTxt.getText().isEmpty()||APaternoTxt.getText().isEmpty()||AMaternoTxt.getText().isEmpty()
                ||matriculaTxt.getText().isEmpty()||matriculaTxt.getText().isEmpty()||materiaTxt.getText().isEmpty()
                ||codMateriaTxt.getText().isEmpty()||asistenciaTxt.getText().isEmpty()||u1Txt.getText().isEmpty()
                ||u2Txt.getText().isEmpty()||u3Txt.getText().isEmpty()||u4Txt.getText().isEmpty()){
            errorTxt.setText("Favor de no dejar espacios vacios");
        }else{
            
            /***************************************************************************************+++
             ******************* esta seccion validará que los datos sean numericos********************+++
             *********************************************************************************************/
            if(ar.isNumeric(matriculaTxt.getText())){
                matricula = Integer.parseInt(matriculaTxt.getText());
                if(ar.isNumeric(asistenciaTxt.getText())){
                    asistencia = Integer.parseInt(asistenciaTxt.getText());
                    if(ar.isNumeric(u1Txt.getText())){
                        u1 = Integer.parseInt(u1Txt.getText());
                        if(ar.isNumeric(u2Txt.getText())){
                            u2 = Integer.parseInt(u2Txt.getText());
                            if(ar.isNumeric(u3Txt.getText())){
                                u3 = Integer.parseInt(u3Txt.getText());
                                if(ar.isNumeric(u4Txt.getText())){
                                    u4 = Integer.parseInt(u4Txt.getText());
                                    if(ar.isValid(u1)){
                                        if(ar.isValid(u2)){
                                            if(ar.isValid(u3)){
                                                if(ar.isValid(u4)){
                                                    if(ar.isValid(asistencia)){
                                                        datosCorrectos=true;   
                                                    }else
                                                        errorTxt.setText("Ingrese valor del 0 al 100 en asistencia");
                                                }else
                                                    errorTxt.setText("Ingrese un valor del 0 al 100 en la U4");
                                            }else
                                                errorTxt.setText("Ingrese un valor del 0 al 100 en la U3");
                                        }else
                                            errorTxt.setText("Ingrese un valor del 0 al 100 en la U2");
                                    }else
                                        errorTxt.setText("Ingrese un valor del 0 al 100 en la U1");
                                }
                                else
                                    errorTxt.setText("Unidad 4 incorrecta ingrese datos numericos");
                            }else
                                errorTxt.setText("Unidad 3 incorrecta ingrese datos numericos");
                        }else
                           errorTxt.setText("Unidad 2 incorrecta ingrese datos numericos"); 
                    }else
                        errorTxt.setText("Unidad 1 incorrecta ingrese datos numericos");
                }else
                    errorTxt.setText("Asistencia incorrecta ingrese datos numericos");
            }else
                errorTxt.setText("Matricula incorrecta ingrese datos numericos");
        
        }
        //se agregaran los valores de las cajas de texto a las variables
        String nombre = nombreTxt.getText();
        String APaterno = APaternoTxt.getText();
        String AMaterno = AMaternoTxt.getText();
        String nombreMateria = materiaTxt.getText();
        String codigoMateria = codMateriaTxt.getText();
        
        //validará que el alumno no sobrepase el limite de materias
        if(ar.contarMaterias(matricula)>=8&&datosCorrectos==true){
                errorTxt.setText("El alumno ya cuenta con 8 materias registradas");
                datosCorrectos=false;
        }
        
        //se contará el numero maximo de alumnos en una materia
        if(ar.contarAlumnosMateria(codigoMateria)>=32&&datosCorrectos==true){
            errorTxt.setText("La materia ya tiene el limite de alumnos registrados");
            datosCorrectos=false;
        }
        
        
        //si todos los datos son correctos y se hicieron todas las validaciones entonces se hara el registro
        if(datosCorrectos==true){
            //se limpiara el campo de texto que arroja los errores
            errorTxt.setText("");

            ArrayList<Materia> materia = new ArrayList<Materia>();
            materia.add(new Materia(nombreMateria,codigoMateria,asistencia,u1,u2,u3,u4,(u1+u2+u3+u4)/4));
            Alumno alumno = new Alumno(nombre,APaterno,AMaterno,matricula,materia);

            try {
                ar.insertarAlumno(alumno);
                errorTxt.setText("Registro exitoso");
            } catch (IOException ex) {
                errorTxt.setText("no se pudo hacer el registro");
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AMaternoTxt;
    private javax.swing.JTextField APaternoTxt;
    private javax.swing.JTextField asistenciaTxt;
    private javax.swing.JTextField codMateriaTxt;
    private javax.swing.JLabel errorTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField materiaTxt;
    private javax.swing.JTextField matriculaTxt;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField u1Txt;
    private javax.swing.JTextField u2Txt;
    private javax.swing.JTextField u3Txt;
    private javax.swing.JTextField u4Txt;
    // End of variables declaration//GEN-END:variables
}
